<?xml version="1.0"?>
<robot name="linorobot2_2wd" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="base_length" value="0.25" />
  <xacro:property name="base_width" value="0.25" />
  <xacro:property name="base_height" value="0.358" />
  <xacro:property name="base_mass" value="1" />

  <xacro:property name="wheel_radius" value="0.045" />
  <xacro:property name="wheel_width" value="0.01" />
  <xacro:property name="wheel_pos_x" value="0.08" />
  <xacro:property name="wheel_pos_y" value="0.12" />
  <xacro:property name="wheel_pos_z" value="-0.04" />
  <xacro:property name="wheel_mass" value=".1" />
  <xacro:property name="wheel_torque" value="20" />
  <xacro:property name="front_caster_wheel" value="false" />
  <xacro:property name="rear_caster_wheel" value="true" />

  <xacro:arg name="use_sim_time" default="false" />
  <xacro:include filename="$(find linorobot2_description)/urdf/mech/base.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/mech/wheel.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/mech/caster_wheel.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/sensors/imu.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/sensors/generic_laser.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/sensors/depth_sensor.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/controllers/diff_drive.urdf.xacro" />
  <xacro:include filename="$(find robot_arm_description)/urdf/arm_mech.urdf.xacro" />

  <xacro:property name="laser_pose">
    <origin xyz="0.0 0 0.325" rpy="-3.1416 0 0"/>
  </xacro:property>

  <xacro:property name="base_laser_pose">
    <origin xyz="0.08 0 -0.05" rpy="-3.1416 0 0"/>
  </xacro:property>

  <xacro:property name="depth_sensor_pose">
    <origin xyz="0.14 0.0 0.23" rpy="0 0 0"/>
  </xacro:property>

  <xacro:base 
    length="${base_length}" 
    width="${base_width}" 
    height="${base_height}" 
    mass="${base_mass}"
    wheel_radius="${wheel_radius}"
    wheel_pos_z="${wheel_pos_z}"
    mesh="file://$(find linorobot2_description)/urdf/mesh/base.stl"
    scale="0.001"
  />

  <xacro:wheel 
    side="left"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${wheel_pos_x}" 
    pos_y="${wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
    rim_mesh="file://$(find linorobot2_description)/urdf/mesh/rim.stl"
    wheel_mesh="file://$(find linorobot2_description)/urdf/mesh/wheel.stl"
    scale="0.001"
  />

  <xacro:wheel 
    side="right"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${wheel_pos_x}" 
    pos_y="${-wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
    rim_mesh="file://$(find linorobot2_description)/urdf/mesh/rim.stl"
    wheel_mesh="file://$(find linorobot2_description)/urdf/mesh/wheel.stl"
    scale="0.001"
  />

  <xacro:if value="${front_caster_wheel}">
    <xacro:caster_wheel 
      side="front"
      mass="0.01"
      base_length="${base_length}" 
      wheel_radius="${wheel_radius}" 
      wheel_pos_z="${wheel_pos_z}" 
    />
  </xacro:if>

  <xacro:if value="${rear_caster_wheel}">
    <xacro:caster_wheel 
      side="rear"
      mass="0.01"
      base_length="${base_length}" 
      wheel_radius="${wheel_radius}" 
      wheel_pos_z="${wheel_pos_z}" 
    />
  </xacro:if>

  <xacro:imu/>

  <xacro:generic_laser>
    <xacro:insert_block name="laser_pose" />
  </xacro:generic_laser>
  
  <xacro:generic_base_laser>
    <xacro:insert_block name="base_laser_pose" />
  </xacro:generic_base_laser>

  <xacro:depth_sensor>
    <xacro:insert_block name="depth_sensor_pose" />
  </xacro:depth_sensor>

  <xacro:diff_drive_controller
    wheel_separation="${wheel_pos_y * 2}"
    wheel_radius="${wheel_radius}"
    wheel_torque="${wheel_torque}"
  />

  <link name="base_mount">
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0" />
        <geometry>
            <mesh filename="file://$(find robot_arm_description)/urdf/meshes/base_mount.stl" scale="0.001 0.001 0.001" />
        </geometry>
      </collision>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0" />
        <geometry>
            <mesh filename="file://$(find robot_arm_description)/urdf/meshes/base_mount.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="black" />
      </visual>
      <inertial>
        <mass value="0.1" />
        <inertia ixx="0.1" iyy="0.1" izz="0.1" ixy="0.0" ixz="0.0" iyz="0.0" />
      </inertial>
  </link>
  <joint name="base_to_arm" type="fixed">
    <parent link="base_link"/>
    <child link="base_mount"/>
    <origin xyz="0 0 0.363" rpy="0 0 0"/>
  </joint>
  <xacro:arm_mech parent="base_mount" use_sim_time="$(arg use_sim_time)" />

</robot>